[package]
name = "stressedselect"
version = "0.1.0"
authors = ["Kevin Chalmers <k.chalmers@napier.ac.uk>"]
[[bin]]
name = "stressedselect"
path = "src/stressedselect.rs"
[dependencies]
time = "0.1.36"
